Add support for parallel build on MacOS
This isn't caught by the Travis CI because it's guarded by the TRAVIS
environment variable being set, but it seems that `sched_getaffinity` is
not available on my MacOS system:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/leonardtruong/repos/pycoreir/setup.py", line 27, in <module>
        njobs = max(2, len(os.sched_getaffinity(0)))
    AttributeError: module 'os' has no attribute 'sched_getaffinity'